project_name: tc2-hat-controller

version: 2

release:
  github:
    owner: TheCacophonyProject
    name: tc2-hat-controller
  name_template: '{{.Tag}}'

builds:
- id: tc2-hat-controller
  binary: tc2-hat-controller
  main: ./cmd/tc2-hat-controller
  goos:
    - linux
  goarch:
    - arm64
  ldflags: -s -w -X main.version={{.Version}} -X main.attinyMajorStr={{ .Env.ATTINY_MAJOR }} -X main.attinyMinorStr={{.Env.ATTINY_MINOR}} -X main.attinyPatchStr={{.Env.ATTINY_PATCH}} -X main.attinyHexHash={{.Env.ATTINY_HASH}}

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <coredev@cacophony.org.nz>
  description: Controls the ATtiny and other device on the Pi HAT
  license: GPL v3.0
  file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  contents:
    - src: _release/raspberrypi-swd.cfg
      dst: /etc/cacophony/raspberrypi-swd.cfg
    - src: _release/org.cacophony.ATtiny.conf
      dst: /etc/dbus-1/system.d/org.cacophony.ATtiny.conf
    - src: _release/org.cacophony.RTC.conf
      dst: /etc/dbus-1/system.d/org.cacophony.RTC.conf
    - src: _release/org.cacophony.i2c.conf
      dst: /etc/dbus-1/system.d/org.cacophony.i2c.conf
    - src: _release/tc2-hat-temp.service
      dst: /etc/systemd/system/tc2-hat-temp.service
    - src: _release/tc2-hat-attiny.service
      dst: /etc/systemd/system/tc2-hat-attiny.service
    - src: _release/tc2-hat-comms.service
      dst: /etc/systemd/system/tc2-hat-comms.service
    - src: _release/stay-on-for
      dst: /usr/bin/stay-on-for
    - src: _release/10-notify-attiny
      dst: /lib/dhcpcd/dhcpcd-hooks/10-notify-attiny
    - src: _release/attiny-firmware.hex
      dst: /etc/cacophony/attiny-firmware.hex
    - src: _release/org.cacophony.beacon.conf
      dst: /etc/dbus-1/system.d/org.cacophony.beacon.conf
    - src: _release/notify-attiny-reboot
      dst: /usr/bin/notify-attiny-reboot
    - src: _release/disable-aux-uart
      dst: /usr/bin/disable-aux-uart
    - src: _release/enable-aux-uart
      dst: /usr/bin/enable-aux-uart
    - src: _release/rpi-reboot.service
      dst: /etc/systemd/system/rpi-reboot.service
    - src: _release/tc2-hat-rtc.service
      dst: /etc/systemd/system/tc2-hat-rtc.service
    - src: _release/tc2-hat-i2c.service
      dst: /etc/systemd/system/tc2-hat-i2c.service
    - src: _release/serial-helper
      dst: /usr/bin/serial-helper
    - src: _release/tc2-hat-attiny
      dst: /usr/bin/tc2-hat-attiny
    - src: _release/tc2-hat-comms
      dst: /usr/bin/tc2-hat-comms
    - src: _release/tc2-hat-i2c
      dst: /usr/bin/tc2-hat-i2c
    - src: _release/tc2-hat-rp2040
      dst: /usr/bin/tc2-hat-rp2040
    - src: _release/tc2-hat-rtc
      dst: /usr/bin/tc2-hat-rtc
    - src: _release/tc2-hat-temp
      dst: /usr/bin/tc2-hat-temp

  dependencies:
    #- python3-pip
    - openocd
  scripts:
    postinstall: "./_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
