#!/bin/bash
# This is to notify if the RPi is going to reboot or shutting down.

if systemctl list-jobs | grep -q 'reboot.target.*start'; then
  # Rebooting
  tc2-hat-attiny write --reg 0x02 --val 0x05
else
  # Shutting down
  tc2-hat-attiny write --reg 0x02 --val 0x02
fi
